### ISSUE TITLE
Remove contacts permission?

### ISSUE THREAD

**Issue by Glitchy-Tozier** [vinaygopinath/launch-chat#26]
Is the currently used permission necessary?
https://github.com/subhamtyagi/openinwa seems to function just fine without it.

**Comment by vinaygopinath** [comment]
Thanks for flagging! I'll take a look when I get to #9, which tracks the implementation of the "Select a contact" feature. In general, I'd love to limit the permissions of this app to only those that it absolutely needs.

That said, I'm not sure how the source repo is able to access contacts (I'll need to understand more about the implementation there), because the [Android documentation says the READ_CONTACTS permission is required](https://developer.android.com/training/contacts-provider/retrieve-names).

**Comment by vinaygopinath** [comment]
I was little confused by this issue and took a brief look because you'll notice that this app's [AndroidManifest.xml does not declare that it uses the contact permission](https://github.com/vinaygopinath/launch-chat/blob/f235e2f40c479b3b924bba6789ac9dbc4ddaef8b/app/src/main/AndroidManifest.xml).

Turns out the READ_CONTACTS and WRITE_CONTACTS permissions were introduced as of 1.1.0 due to the use of the [vcard4android](https://github.com/bitfireAT/vcard4android/blob/adf00bd98a5241982097de1f81faaed7078f0158/lib/src/main/AndroidManifest.xml) library in the implementation of the ["Register as a handler of shared contacts" feature](https://github.com/vinaygopinath/launch-chat/issues/11), which is a new feature in this app compared to the source repo. 

As long as this app supports receiving exported VCF (contact) files and uses this library (and possibly even with other libraries), it's not possible to remove the READ_CONTACTS and WRITE_CONTACTS permission, even though this app does not access contacts in circumstances other than reading the contact shared with it, and does not _write_ to contacts at all.

**Comment by Glitchy-Tozier** [comment]
Understood, thank you for the explanation!
